name: clang-tidy

on:
  pull_request:
      branches:
      - master
  workflow_dispatch:
    inputs:
      check_type:
        type: choice
        description: "Choose the type of check you want to run"
        options:
          - "readability"
          - "performance"
          - "modernize"

jobs:

  build-linux:
    name: Build on Linux
    if: ${{ always() }}
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Prepare for Build
      id: prepare
      run: |
        sudo apt install ninja-build clang-14

    - name: Configure for Build
      id: configure
      run: |
        cd simulation
        cmake --preset lin-clang-rel

    - name: Build
      id: build
      run: |
        cd simulation
        cmake --build --preset lin-clang-rel
