name: firebase-deploy
on:
  push:
      branches:
      - master
      paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ECOSYSTEM_SIMULATION }}'
          channelId: live
          projectId: ecosystem-simulation
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
